language: c

matrix:
    include:
        - os:
            - linux
            - osx

compiler:
    - gcc
    - clang

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - cmake --clean ..
    - cmake --build ..

after_success:
    - python test/test.py --dir=
