language: c

matrix:
    include:
        - os: linux
          compiler: gcc
        - os: linux
          compiler: clang
        - os: osx
          compiler: gcc
          env: TOOL="-DUSE_LIBCOMP=ON"
        - os: osx
          compiler: clang
          env: TOOL="-DUSE_LIBCOMP=ON"
        - os: windows
          compiler: gcc
        - os: windows
          compiler: clang

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libbsd-dev; fi

before_script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TEST=ON $TOOL

script:
    - make
