language: c

matrix:
    include:
        - os:
            - linux

compiler:
    - clang
    - gcc

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make -DBUILD_TEST=ON

after_success:
    - cd ../test
    - python test.py --exe_dir=../build
