language: c

matrix:
    include:
        - os:
            - linux
          env: CFLAGS="-std=c99"

compiler:
    - clang
    - gcc

before_script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TEST=ON

script: make

after_success:
    - cd ../test
    - python test.py --exe_dir=../build
