language: c

matrix:
    include:
        - os: windows
          compiler: clang
        - os: windows
          compiler: gcc

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libbsd-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update;                     fi
    - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install zlib;               fi

before_script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TEST=ON $TOOL

script:
    - make
