language: c

matrix:
    include:
        - os:
            - linux

compiler:
    - clang

before_script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TEST=ON

script: make

after_success:
    - cd ../test
    - python test.py --exe_dir=../build
