language: c

matrix:
    include:
        - os:
            - linux

compiler:
    - gcc

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make

after_success:
    - python test/test.py --dir=
