language: c

matrix:
    include:
        - os: windows
          compiler: clang
        - os: windows
          compiler: clang 
          env: TOOL="-DUSE_PKCRYPT=OFF -DUSE_AES=OFF"
        - os: windows
          compiler: gcc
        - os: linux
          compiler: clang
        - os: linux
          compiler: clang 
          env: TOOL="-DUSE_ZLIB=OFF"
        - os: linux
          compiler: clang 
          env: TOOL="-DUSE_BZIP=OFF"
        - os: linux
          compiler: clang 
          env: TOOL="-DUSE_LZMA=OFF"
        - os: linux
          compiler: clang 
          env: TOOL="-DUSE_AES=OFF"
        - os: linux
          compiler: clang 
          env: TOOL="-DUSE_PKCRYPT=OFF"
        - os: linux
          compiler: clang 
          env: TOOL="-DCOMPRESS_ONLY=ON"
        - os: linux
          compiler: clang 
          env: TOOL="-DDECOMPRESS_ONLY=ON"
        - os: linux
          compiler: clang 
          env: TOOL="-DUSE_PKCRYPT=OFF -DUSE_AES=OFF"
        - os: linux
          compiler: clang 
          env: TOOL="-DUSE_OPENSSL=ON"
        - os: linux
          compiler: gcc
        - os: osx
          compiler: clang
        - os: osx
          compiler: gcc
        - os: osx
          compiler: clang
          env: TOOL="-DUSE_LIBCOMP=ON"
        - os: osx
          compiler: gcc
          env: TOOL="-DUSE_LIBCOMP=ON"
        - os: osx
          compiler: clang 
          env: TOOL="-DUSE_OPENSSL=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl"

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libbsd-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libssl-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install openssl; fi

before_script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TEST=ON $TOOL

script:
    - cmake --build .
