language: c

matrix:
    include:
        - os:
            - linux

compiler:
    - clang

before_script:  
    - cmake .

script: make

after_success:
    - cd test
    - python test.py --exe_dir=../Debug
