language: c

os:
    - linux
    - windows

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get install libbsd-dev

before_script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TEST=ON

script:
    - make
